//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remembrance.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remembrance.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the manual translation because it will lead to the abscence of translations..
        /// </summary>
        public static string CannotDeleteManual {
            get {
                return ResourceManager.GetString("CannotDeleteManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot detect language for the word..
        /// </summary>
        public static string CannotDetectLanguage {
            get {
                return ResourceManager.GetString("CannotDetectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download image..
        /// </summary>
        public static string CannotDownloadImage {
            get {
                return ResourceManager.GetString("CannotDownloadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get Qwant image search results..
        /// </summary>
        public static string CannotGetQwantResults {
            get {
                return ResourceManager.GetString("CannotGetQwantResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import word &apos;{0}&apos;..
        /// </summary>
        public static string CannotImportWord {
            get {
                return ResourceManager.GetString("CannotImportWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot list languages..
        /// </summary>
        public static string CannotListLanguages {
            get {
                return ResourceManager.GetString("CannotListLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot predict possible options..
        /// </summary>
        public static string CannotPredict {
            get {
                return ResourceManager.GetString("CannotPredict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot speak the word..
        /// </summary>
        public static string CannotSpeak {
            get {
                return ResourceManager.GetString("CannotSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot synchronize {0} in {1}..
        /// </summary>
        public static string CannotSynchronize {
            get {
                return ResourceManager.GetString("CannotSynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot translate word &apos;{0}&apos;..
        /// </summary>
        public static string CannotTranslate {
            get {
                return ResourceManager.GetString("CannotTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured..
        /// </summary>
        public static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed.
        /// </summary>
        public static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following words were not imported.
        /// </summary>
        public static string ImportErrors {
            get {
                return ResourceManager.GetString("ImportErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed.
        /// </summary>
        public static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The languages pair {0} -&gt; {1} is unsupported..
        /// </summary>
        public static string InvalidTargetLanguage {
            get {
                return ResourceManager.GetString("InvalidTargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No translations have been found for the word..
        /// </summary>
        public static string NoAssessmentTranslations {
            get {
                return ResourceManager.GetString("NoAssessmentTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image cannot be found for the word &apos;{0}&apos;..
        /// </summary>
        public static string NoMoreImages {
            get {
                return ResourceManager.GetString("NoMoreImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No translations have been found for the word &apos;{0}&apos;..
        /// </summary>
        public static string NoTranslations {
            get {
                return ResourceManager.GetString("NoTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such translation is already added to the list..
        /// </summary>
        public static string TranslationIsPresent {
            get {
                return ResourceManager.GetString("TranslationIsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word is missing..
        /// </summary>
        public static string WordIsMissing {
            get {
                return ResourceManager.GetString("WordIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word has already been added to the dictionary..
        /// </summary>
        public static string WordIsPresent {
            get {
                return ResourceManager.GetString("WordIsPresent", resourceCulture);
            }
        }
    }
}
