//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remembrance.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remembrance.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start showing cards.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add process to blacklist.
        /// </summary>
        public static string AddProcessToBlacklist {
            get {
                return ResourceManager.GetString("AddProcessToBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add translation.
        /// </summary>
        public static string AddTranslation {
            get {
                return ResourceManager.GetString("AddTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide an answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you&apos;d like to delete the translation {0}?.
        /// </summary>
        public static string AreYouSureDelete {
            get {
                return ResourceManager.GetString("AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The browser was opened at qwant.com. Please confirm that you are not a robot..
        /// </summary>
        public static string BrowserWasOpened {
            get {
                return ResourceManager.GetString("BrowserWasOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card show frequency.
        /// </summary>
        public static string CardShowFrequency {
            get {
                return ResourceManager.GetString("CardShowFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card was visible for.
        /// </summary>
        public static string CardVisiblePauseTime {
            get {
                return ResourceManager.GetString("CardVisiblePauseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter.
        /// </summary>
        public static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! The answer is correct.
        /// </summary>
        public static string CorrectAnswer {
            get {
                return ResourceManager.GetString("CorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop showing cards.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete translation.
        /// </summary>
        public static string DeleteTranslation {
            get {
                return ResourceManager.GetString("DeleteTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demote learning rank.
        /// </summary>
        public static string Demote {
            get {
                return ResourceManager.GetString("Demote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        public static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit manual translations.
        /// </summary>
        public static string EditManualTranslations {
            get {
                return ResourceManager.GetString("EditManualTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings.
        /// </summary>
        public static string EditSettings {
            get {
                return ResourceManager.GetString("EditSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the answer:.
        /// </summary>
        public static string EnterTheAnswer {
            get {
                return ResourceManager.GetString("EnterTheAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export succeeded.
        /// </summary>
        public static string ExportSucceeded {
            get {
                return ResourceManager.GetString("ExportSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string FromCap {
            get {
                return ResourceManager.GetString("FromCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag columns here for grouping.
        /// </summary>
        public static string GridGroupHeader {
            get {
                return ResourceManager.GetString("GridGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import succeeded. {0} words imported.
        /// </summary>
        public static string ImportSucceeded {
            get {
                return ResourceManager.GetString("ImportSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✭.
        /// </summary>
        public static string IsFavorited {
            get {
                return ResourceManager.GetString("IsFavorited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last card show time.
        /// </summary>
        public static string LastCardShowTime {
            get {
                return ResourceManager.GetString("LastCardShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn this word.
        /// </summary>
        public static string LearnWord {
            get {
                return ResourceManager.GetString("LearnWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading failed.
        /// </summary>
        public static string LoadingFailed {
            get {
                return ResourceManager.GetString("LoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaning.
        /// </summary>
        public static string Meaning {
            get {
                return ResourceManager.GetString("Meaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mistakes are automatically corrected. The number of possible mistakes depends on the word&apos;s length.
        /// </summary>
        public static string MistakesTooltip {
            get {
                return ResourceManager.GetString("MistakesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сhanged.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next card show time.
        /// </summary>
        public static string NextCardShowTime {
            get {
                return ResourceManager.GetString("NextCardShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show translation details.
        /// </summary>
        public static string OpenDetails {
            get {
                return ResourceManager.GetString("OpenDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings folder.
        /// </summary>
        public static string OpenSettingsFolder {
            get {
                return ResourceManager.GetString("OpenSettingsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open shared folder.
        /// </summary>
        public static string OpenSharedFolder {
            get {
                return ResourceManager.GetString("OpenSharedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of speech.
        /// </summary>
        public static string PartOfSpeech {
            get {
                return ResourceManager.GetString("PartOfSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active blacklisted process.
        /// </summary>
        public static string PauseReasonActiveProcessBlacklisted {
            get {
                return ResourceManager.GetString("PauseReasonActiveProcessBlacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card is being shown now.
        /// </summary>
        public static string PauseReasonCardIsVisible {
            get {
                return ResourceManager.GetString("PauseReasonCardIsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive mode.
        /// </summary>
        public static string PauseReasonInactiveMode {
            get {
                return ResourceManager.GetString("PauseReasonInactiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation in progress.
        /// </summary>
        public static string PauseReasonOperationInProgress {
            get {
                return ResourceManager.GetString("PauseReasonOperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Language.
        /// </summary>
        public static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause when processes are active.
        /// </summary>
        public static string ProcessesBlacklist {
            get {
                return ResourceManager.GetString("ProcessesBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path.
        /// </summary>
        public static string ProcessFilePath {
            get {
                return ResourceManager.GetString("ProcessFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string ProcessIcon {
            get {
                return ResourceManager.GetString("ProcessIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random translation choice.
        /// </summary>
        public static string RandomTranslation {
            get {
                return ResourceManager.GetString("RandomTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse translation.
        /// </summary>
        public static string ReverseTranslation {
            get {
                return ResourceManager.GetString("ReverseTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next image.
        /// </summary>
        public static string SetNextImage {
            get {
                return ResourceManager.GetString("SetNextImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous image.
        /// </summary>
        public static string SetPreviousImage {
            get {
                return ResourceManager.GetString("SetPreviousImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show active processes.
        /// </summary>
        public static string ShowActiveProcesses {
            get {
                return ResourceManager.GetString("ShowActiveProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show #.
        /// </summary>
        public static string ShowCount {
            get {
                return ResourceManager.GetString("ShowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak.
        /// </summary>
        public static string Speak {
            get {
                return ResourceManager.GetString("Speak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync using.
        /// </summary>
        public static string SyncBus {
            get {
                return ResourceManager.GetString("SyncBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time left to show card.
        /// </summary>
        public static string TimeToShow {
            get {
                return ResourceManager.GetString("TimeToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remembrance - Memorize words easily.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string ToCap {
            get {
                return ResourceManager.GetString("ToCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle translation priority.
        /// </summary>
        public static string TogglePriority {
            get {
                return ResourceManager.GetString("TogglePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTS Speaker.
        /// </summary>
        public static string TtsSpeaker {
            get {
                return ResourceManager.GetString("TtsSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ui Language.
        /// </summary>
        public static string UiLanguage {
            get {
                return ResourceManager.GetString("UiLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View logs.
        /// </summary>
        public static string ViewLogs {
            get {
                return ResourceManager.GetString("ViewLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with custom translation.
        /// </summary>
        public static string WithCustomTranslation {
            get {
                return ResourceManager.GetString("WithCustomTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong answer!.
        /// </summary>
        public static string WrongAnswer {
            get {
                return ResourceManager.GetString("WrongAnswer", resourceCulture);
            }
        }
    }
}
