//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remembrance.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WordMetadata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordMetadata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remembrance.View.WordMetadata", typeof(WordMetadata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adj.
        /// </summary>
        internal static string Adjective {
            get {
                return ResourceManager.GetString("Adjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adv.
        /// </summary>
        internal static string Adverb {
            get {
                return ResourceManager.GetString("Adverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apart.
        /// </summary>
        internal static string AdverbialParticiple {
            get {
                return ResourceManager.GetString("AdverbialParticiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conj.
        /// </summary>
        internal static string Conjunction {
            get {
                return ResourceManager.GetString("Conjunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noun.
        /// </summary>
        internal static string Noun {
            get {
                return ResourceManager.GetString("Noun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to num.
        /// </summary>
        internal static string Numeral {
            get {
                return ResourceManager.GetString("Numeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to part.
        /// </summary>
        internal static string Participle {
            get {
                return ResourceManager.GetString("Participle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to particle.
        /// </summary>
        internal static string Particle {
            get {
                return ResourceManager.GetString("Particle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prep.
        /// </summary>
        internal static string Preposition {
            get {
                return ResourceManager.GetString("Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pron.
        /// </summary>
        internal static string Pronoun {
            get {
                return ResourceManager.GetString("Pronoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verb.
        /// </summary>
        internal static string Verb {
            get {
                return ResourceManager.GetString("Verb", resourceCulture);
            }
        }
    }
}
